# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target KDE4Workspace__kworkspace
ADD_LIBRARY(KDE4Workspace__kworkspace SHARED IMPORTED)
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
# Include library additions
FILE(GLOB INCLUDE_FILES "${_DIR}/librarydefs`-*.cmake")
FOREACH(f ${INCLUDE_FILES})
	INCLUDE(${f})
ENDFOREACH(f)

# Load information for each installed configuration.
FILE(GLOB CONFIG_FILES "${_DIR}/KDE4WorkspaceLibraryTargets-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
