#!/bin/sh

METADATA_MIRROR=rsync://gentoo.kynes.de:660/gentoo-metadata-kde/

if [[ "$(basename $(pwd))" == "Documentation" ]] ; then
	echo "Syncing KDE overlay metadata ..."
	exec rsync --quiet --recursive --times --compress --delete-delay $METADATA_MIRROR ../metadata/cache/
else
	echo "ERROR: This script is meant to be run from within Documentation/ !"
	exit 255
fi
